from django.urls import path
from . import views

urlpatterns = [
    path('', views.classroom_list, name='classroom_list'),  # View all classrooms
    path('tasks/', views.task_list, name='task_list'),  # View all tasks
    path('create/', views.create_classroom, name='create_classroom'),  # Create a new class
    path('join/', views.join_classroom, name='join_classroom'),  # Join a classroom
    path('<int:classroom_id>/', views.classroom_detail, name='classroom_detail'),  # View class details
    path('<int:classroom_id>/announcement/add/', views.add_announcement, name='add_announcement'),
    path('<int:classroom_id>/assignment/add/', views.add_assignment, name='add_assignment'),  # Add assignment
    path('announcement/<int:announcement_id>/delete/', views.delete_announcement, name='delete_announcement'),  # Delete announcement
    path('assignment/<int:assignment_id>/delete/', views.delete_assignment, name='delete_assignment'),  # Delete assignment
    path('announcement/<int:announcement_id>/', views.view_announcement, name='view_announcement'),  # View announcement
    path('announcement/<int:announcement_id>/edit/', views.edit_announcement, name='edit_announcement'),  # Edit announcement
    path('assignment/<int:assignment_id>/', views.view_assignment, name='view_assignment'),  # View assignment
    path('assignment/<int:assignment_id>/edit/', views.edit_assignment, name='edit_assignment'),  # Edit assignment
    path('assignment/<int:assignment_id>/submit/', views.submit_assignment, name='submit_assignment'),  # Submit assignmen
    path('submission/<int:submission_id>/edit/', views.edit_submission, name='edit_submission'),  # Edit submission
    path('submission/<int:submission_id>/cancel/', views.cancel_submission, name='cancel_submission'),  # Cancel submission
    path('assignment/<int:assignment_id>/submissions/', views.view_submissions, name='view_submissions'),
    path('<str:object_type>/<int:object_id>/comments/', views.view_comments, name='view_comments'),  # View comments
    path('comment/<int:comment_id>/reply/', views.add_reply, name='add_reply'),  # Add reply
    path('<int:classroom_id>/students/', views.view_students, name='view_students'),  # View all students
    path('<int:classroom_id>/students/<int:student_id>/delete/', views.delete_student, name='delete_student'),  # Delete student
    path('<int:classroom_id>/add-student/', views.add_student, name='add_student'),  # Add student by email
    path('<int:classroom_id>/delete/', views.delete_classroom, name='delete_classroom'),  # Delete classroom
    path('<int:classroom_id>/leave/', views.leave_classroom, name='leave_classroom'),  # Leave classroom
    path('invitations/accept/<int:invitation_id>/', views.accept_invitation, name='accept_invitation'),
    path('invitations/', views.invitations, name='invitations'),
    path('<int:classroom_id>/quiz/create/info/', views.create_quiz_info, name='create_quiz_info'),
    path('<int:classroom_id>/quiz/create/questions/', views.create_quiz_questions, name='create_quiz_questions'),
    path('quiz/<int:quiz_id>/', views.view_quiz, name='view_quiz'),
    path('quiz/<int:quiz_id>/delete/', views.delete_quiz, name='delete_quiz'),
    path('quiz/<int:quiz_id>/submit/', views.submit_quiz, name='submit_quiz'),
    path('quiz/<int:quiz_id>/submissions/', views.view_quiz_submissions, name='view_quiz_submissions'),
    path('submission/quiz/<int:submission_id>/', views.grade_quiz_submission, name='grade_quiz_submission'),
    path('quiz/<int:quiz_id>/download/', views.download_quiz_results, name='download_quiz_results'),
    path('features/', views.classconnect_features, name='classconnect_features'),
    path('quiz/<int:quiz_id>/analytics/', views.quiz_analytics, name='quiz_analytics'),
    path('quiz/<int:quiz_id>/analytics/pdf/', views.download_quiz_analytics_pdf, name='download_quiz_analytics_pdf'),
    path('classroom/<int:classroom_id>/discussion/', views.discussion_forum, name='discussion_forum'),
    path('discussion/thread/<int:thread_id>/', views.discussion_thread, name='discussion_thread'),
    path('discussion/message/<int:message_id>/react/<str:reaction>/', views.add_message_reaction, name='add_message_reaction'),
    path('discussion/message/<int:message_id>/reply/', views.reply_to_message, name='reply_to_message'),
    path('discussion/thread/<int:thread_id>/toggle-pin/', views.toggle_pin_thread, name='toggle_pin_thread'),
    path('discussion/thread/<int:thread_id>/delete/', views.delete_thread, name='delete_thread'),
    path('change-credentials/verify/', views.verify_current_credentials, name='verify_current_credentials'),
    path('change-credentials/send-code/', views.send_verification_code, name='send_verification_code'),
    path('change-credentials/verify-code/', views.verify_update_credentials, name='verify_update_credentials'),
    path('change-credentials/resend-code/', views.resend_verification_code, name='resend_verification_code'),
    path('quiz/<int:quiz_id>/share-results/', views.share_quiz_results_as_announcement, name='share_quiz_results'),
]
